// Auto-generated font atlas metadata
// Font: unscii-16
// Generated by: create_unscii_font_atlas_hires.py
// High-resolution antialiased rendering

#pragma once

#include <cstdint>

struct FONT_ATLAS_UNSCII_16 {
    static constexpr int ATLAS_WIDTH = 512;
    static constexpr int ATLAS_HEIGHT = 512;
    static constexpr int GLYPH_WIDTH = 8;
    static constexpr int GLYPH_HEIGHT = 16;
    static constexpr int PADDING = 4;
    static constexpr int SPACING = 2;
    static constexpr int GLYPHS_PER_ROW = 16;
    static constexpr int ROWS = 14;
    static constexpr int CHAR_COUNT = 222;
    static constexpr int FIRST_CHAR = 32;
    static constexpr int LAST_CHAR = 126;
    static constexpr int RENDER_SCALE = 2;
    static constexpr bool ANTIALIASED = true;
    static constexpr bool HAS_ALPHA = true;
    static constexpr const char* FORMAT = "RGBA";
    static constexpr const char* FILENAME = "font_atlas_unscii_unscii-16_8x16.png";
};
